# Site settings
title: Luis Zaman
email: luis.zaman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Luis Zaman's personal website built on github.io pages. My academic work
  focuses on host-parasite coevolution, and sometimes much more broadly on 
  fundamental questions in evolution. All my work takes an integrative angle
  trying to take advantage of the best tools and techniques to answer the questions
  I'm most fascinated by.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://labfab.cc.com" # the base hostname & protocol for your site
twitter_username: luiszaman
github_username:  zamanlh

# Build settings
markdown: kramdown

collections:
  - project